homeassistant:
  name: Home
  latitude: 38.9734316
  longitude: -76.4984651
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  unit_system: imperial
  time_zone: America/New_York
  # auth_providers:
  #   - type: homeassistant
  #   - type: legacy_api_password   # backwards compat API password support
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  # Specify handling of js: es5=compile to es5, latest=use new features, auto=default
  # Floorplan files (panels/*.html) have been written with new js features and
  # don't seem to be compiled to es5. 'auto' attempts to load es5 on
  # FullyBrowsers which failes. Force 'latest' here.
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.b031b2a424.html
    # - /local/custom_ui/state-card-stock-price.html
  themes: !include themes.yaml

# customizer:
#   custom_ui: local

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Use pushover.net for notifications
notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: mqtt_say
    platform: command_line
    command: '/config/bin/mqtt-tts.sh'

# Load custom panels (floorplan)
panel_custom: !include_dir_merge_list custom_panels
