homeassistant:
  name: Home
  latitude: 38.9734316
  longitude: -76.4984651
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_api_password
  base_url: hass.markandcarrie.com

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:

recorder: !include recorder.yaml

# Record events in influxdb
influxdb:
  host: 192.168.1.201
  port: 8086
  # exclude:
  #   entities:
  #     - ensor.livingroom_real_feel


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# z-wave and zibgee keep dropping (dead/cached) under home assistant
# moving all z-wave/zibgee back to smart things and using smarter
# smartthings to interact with those devices
#
# zwave:
#   usb_path: /dev/ttyUSB0
#   network_key: !secret zwave_network_key
#
# zha:
#   usb_path: /dev/ttyUSB1
#   database_path: /var/lib/hass/zibgee.db

mqtt:
  broker: mqtt
  port: 1883
  username: hass
  password: !secret mqtt_password

device_tracker:
  - platform: actiontec
    host: 192.168.1.1
    username: !secret fios_username
    password: !secret fios_password
    new_device_defaults:
      track_new_devices: false
  - platform: owntracks

# Text to speech
tts:
  - platform: google

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

map:

python_script:

media_player:
  - platform: squeezebox
    name: lms
    host: 127.0.0.1
    port: 9001

# media_player:
#    - platform: cast

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config:
      config: /local/custom_ui/floorplan/floorplan.yaml
      # hide_app_toolbar:
  - name: clock
    sidebar_title: Clock
    sidebar_icon: mdi:alarm
    url_path: clock
    config:
      config: /local/custom_ui/floorplan/floorclock.yaml
      hide_app_toolbar:
  - name: pets
    sidebar_title: Pets
    sidebar_icon: mdi:paw
    url_path: pets
    config:
      config: /local/custom_ui/floorplan/floorpets.yaml
      hide_app_toolbar:

# Allow Amazon Echo to control some things
emulated_hue: !include alexa.yaml
logger: !include logger.yaml
light: !include_dir_merge_list lights
wemo: !include wemo.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include zones.yaml
lock: !include_dir_merge_list locks
nest: !include nest.yaml
script: !include_dir_merge_named scripts
automation: !include_dir_merge_list automations
shell_command: !include_dir_merge_named shell_commands
group: !include_dir_merge_named groups
