version: '3'
services:
  web:
    image: homeassistant/home-assistant:0.73.2
    # ports:
    #   - "8123:8123"
    #   - "8300:8300"  # emulated_hue
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      # zwave
      # - /dev/ttyUSB0:/dev/ttyUSB0
      # zigbee
      # - /dev/ttyUSB1:/dev/ttyUSB1
      # modem
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
