version: '3'
services:
  web:
    image: homeassistant/home-assistant:0.76.2
    # ports:
    #   - "8123:8123"
    #   - "8300:8300"  # emulated_hue
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0     # zwave
      # - /dev/ttyUSB1:/dev/ttyUSB1   # zigbee
      - /dev/ttyACM0:/dev/ttyACM0     # modem
    restart: always
    network_mode: host
