# Toggle to set home mode

input_boolean:
  home_mode:
    name: 'Home Mode'
    icon: 'mdi:home'

automation:
  - alias: 'Home Mode: Home - nest home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.home_mode
        from: 'off'
        to: 'on'
    action:
      service: script.nest_home

  - alias: 'Home Mode: Away - nest away'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.home_mode
        from: 'on'
        to: 'off'
    action:
      - delay: 00:15:00
      - service: script.nest_away

  # --- When arrive Home adjust temps ---
  - alias: 'Home Mode: Home - adj therm targets'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.home_mode
        to: 'on'
      - platform: state
        entity_id: input_boolean.windows_open_mode
        to: 'off'
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
        - condition: state
          entity_id: input_boolean.renting_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.windows_open_mode
          state: 'off'
    action:
      service: script.set_temp_targets_home

  # --- When departing Home adjust temps ---
  - alias: 'Home Mode: Away - adj therm targets'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.home_mode
        to: 'off'
      - platform: state
        entity_id: input_boolean.windows_open_mode
        to: 'off'
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: 'off'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.renting_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.windows_open_mode
          state: 'off'
    action:
      service: script.set_temp_targets_away

  # --- When Home adjust temps at night ---
  - alias: 'Night Mode: Update Thermostat Targets'
    initial_state: 'on'
    trigger:
      platform: time
      at: '22:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.renting_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.windows_open_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
    action:
      service: script.set_temp_targets_night

  # --- When Home adjust temps in the morning ---
  - alias: 'End Night Mode: Update Thermostat Targets'
    initial_state: 'on'
    trigger:
      platform: time
      at: '6:30:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.renting_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.windows_open_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
    action:
      service: script.set_temp_targets_home


script:
  set_temp_targets_home:
    sequence:
      - service: script.set_temp_targets
        data_template:
          rear_heating_target: "{{ states.input_number.rear_heating_target_home.state }}"
          rear_cooling_target: "{{ states.input_number.rear_cooling_target_home.state }}"
          front_heating_target: "{{ states.input_number.front_heating_target_home.state }}"
          front_cooling_target: "{{ states.input_number.front_cooling_target_home.state }}"

  set_temp_targets_away:
    sequence:
      - service: script.set_temp_targets
        data_template:
          rear_heating_target: "{{ states.input_number.rear_heating_target_away.state }}"
          rear_cooling_target: "{{ states.input_number.rear_cooling_target_away.state }}"
          front_heating_target: "{{ states.input_number.front_heating_target_away.state }}"
          front_cooling_target: "{{ states.input_number.front_cooling_target_away.state }}"

  set_temp_targets_night:
    sequence:
      - service: script.set_temp_targets
        data_template:
          rear_heating_target: "{{ states.input_number.rear_heating_target_night.state }}"
          rear_cooling_target: "{{ states.input_number.rear_cooling_target_night.state }}"
          front_heating_target: "{{ states.input_number.front_heating_target_night.state }}"
          front_cooling_target: "{{ states.input_number.front_cooling_target_night.state }}"
