# Toggle to set renting mode

homeassistant:

input_boolean:
  renting_mode:
    name: 'Renting'
    icon: 'mdi:currency-usd'

automation:

  # --- When Renting opened adjust temps ---
  - alias: 'Renting Mode: adj therm targets'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.renting_mode
      to: 'on'
    condition:
      condition: state
      entity_id: input_boolean.windows_open_mode
      state: 'off'
    action:
      service: script.set_temp_targets_renting

script:
  set_temp_targets_renting:
    sequence:
      - service: script.set_temp_targets
        data_template:
          rear_heating_target: "{{ states.input_number.rear_heating_target_renting.state }}"
          rear_cooling_target: "{{ states.input_number.rear_cooling_target_renting.state }}"
          front_heating_target: "{{ states.input_number.front_heating_target_renting.state }}"
          front_cooling_target: "{{ states.input_number.front_cooling_target_renting.state }}"
