# Toggle to set window open mode

homeassistant:

input_boolean:
  windows_open_mode:
    name: 'Windows Open'
    icon: 'mdi:window-closed'

automation:

  # --- When Windows opened adjust temps ---
  - alias: 'Window Open Mode: adj therm targets'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.windows_open_mode
      to: 'on'
    condition:
    action:
      service: script.set_temp_targets_windows_open

script:
  set_temp_targets_windows_open:
    sequence:
      - service: script.set_temp_targets
        data_template:
          rear_heating_target: 50
          rear_cooling_target: 110
          front_heating_target: 50
          front_cooling_target: 110
