# Toggle to set window open mode

homeassistant:

input_boolean:
  windows_open_mode:
    name: 'Windows Open'
    icon: 'mdi:window-closed'

automation:

  # --- When Windows opened adjust temps ---
  - alias: 'Window Open Mode: adj therm targets'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_boolean.windows_open_mode
      to: 'on'
    condition:
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.rear_heating_target
          value: 50
      - service: input_number.set_value
        data_template:
          entity_id: input_number.rear_cooling_target
          value: 110
      - service: input_number.set_value
        data_template:
          entity_id: input_number.front_heating_target
          value: 50
      - service: input_number.set_value
        data_template:
          entity_id: input_number.front_cooling_target
          value: 110
