homeassistant:
  customize:
    group.front_thermostat:
      friendly_name: 'Front Temps/Thermostat'
      icon: mdi:fan
    sensor.front_temps:
      icon: mdi:thermometer

sensor:
  - platform: min_max
    name: "Front Temps"
    type: mean  # min, max, mean
    round_digits: 1
    entity_ids:
      - sensor.den_thermostat_temp
      - sensor.girls_br_temp

input_select:
  # --- Front Thermostate Mode dropdown ---
  front_thermostat_mode:
    name: Front Thermostat Mode
    options:
      - "auto"
      - "off"
      - "cool"
      - "heat"
    icon: mdi:fan

input_number:
  # -- Front Therm targets ---
  front_heating_target:
    name: Front Heating Target
    initial: 68
    min: 55
    max: 72
    step: 1

  front_cooling_target:
    name: Front Cooling Target
    initial: 76
    min: 70
    max: 85
    step: 1

group:
  front_thermostat:
    - sensor.front_temps
    - input_select.front_thermostat_mode
    # - switch.front_thermostat_fan_mode
    - sensor.den_thermostat_current_state
    - input_number.front_heating_target
    - input_number.front_cooling_target

automation:

  # --- Front Thermostat ---
  # Keep mode in sync b/w MQTT/dropdown
  - alias: Set Front Thermostat Mode Selector
    trigger:
      - platform: mqtt
        topic: "smartthings/Den Thermostat/thermostatMode"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.front_thermostat_mode
          option: '{{ trigger.payload }}'
  - alias: Set Front Thermostat Mode
    trigger:
      - platform: state
        entity_id: input_select.front_thermostat_mode
      # Might need for this and for setpoint
      # - platform: event
      #   event_type: state_change
      #   event_data:
      #     entity_id: sensor.front_thermostat_current_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: "smartthings/Den Thermostat/thermostatMode"
          payload: '{{ states.input_select.front_thermostat_mode.state }}'
          retain: true

  # Adj Den Thermostat to meet Front Temp (heat)
  - alias: Front Heating Target Set
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: input_number.front_heating_target
      - platform: state
        entity_id: input_select.front_thermostat_mode
      - platform: state
        entity_id: sensor.front_temps
    condition:
      condition: state
      entity_id: input_select.front_thermostat_mode
      state: 'heat'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.den_heating_target
          value: >-
            {%  set temp = { "observed":   float(states.sensor.front_temps.state),
                             "target":     float(states.input_number.front_heating_target.state),
                             "thermostat": float(states.sensor.den_thermostat_temp.state) } %}
            {% if temp.observed < temp.target - 1 %}
                {{ [ temp.thermostat + 1.5, 70 ] | min }}
            {% elif temp.observed >= temp.target - 1 %}
                {{ [ temp.thermostat - 1.5, 50 ] | max }}
            {% endif %}
      - service: system_log.write
        data_template:
          message: >-
            Changing den_heating_target to {{ states.sensor.den_heating_target.state }}
          level: info

  # Adj kitchen Thermostat to meet Front Temp (a/c)
  - alias: Front A/C Target Set
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: input_number.rear_cooling_target
      - platform: state
        entity_id: input_select.rear_thermostat_mode
      - platform: state
        entity_id: sensor.rear_temps
    condition:
      condition: state
      entity_id: input_select.rear_thermostat_mode
      state: 'cool'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.kitchen_cooling_target
          value: >-
            {%  set temp = { "observed":   float(states.sensor.rear_temps.state),
                             "target":     float(states.input_number.rear_cooling_target.state),
                             "thermostat": float(states.sensor.kitchen_thermostat_temp.state) } %}
            {% if temp.observed > temp.target + 1 %}
                {{ [ temp.thermostat - 1.5, 64 ] | max }}
            {% elif temp.observed <= temp.target + 1 %}
                {{ [ temp.thermostat - 1.5, 80 ] | min }}
            {% endif %}
      - service: system_log.write
        data_template:
          message: >-
            Changing kitchen_cooling_target to {{ states.sensor.kitchen_cooling_target.state }}
          level: info
