homeassistant:
  customize:
    group.front_thermostat:
      friendly_name: 'Front Temps/Thermostat'
      icon: mdi:fan
    sensor.front_temps:
      icon: mdi:thermometer
    input_select.front_function:
      persistent: true
    input_number.front_heating_target:
      persistent: true
    input_number.front_cooling_target:
      persistent: true

sensor:
  - platform: template
    sensors:
      front_temps:
        friendly_name: "Front Temps"
        unit_of_measurement: '°F'
        entity_id:
          - sensor.den_thermostat_temp
          - sensor.girls_br_temp
          - sensor.office_temp
          - input_boolean.den_thermostat_occupied
          - input_boolean.girls_br_occupied
          - input_boolean.office_occupied
          - input_select.front_function
        value_template: >
            {% macro mean(values) -%}
               {{- (values|sum) / (values|length) -}}
            {%- endmacro %}
            {% macro get_temp(rooms) -%}
              {% for room in rooms -%}
                {%- if states.input_boolean[room ~ "_occupied"].state == "on" -%}
                  {{-states.sensor[room ~ "_temp"].state-}},
                {%- endif -%}
              {%- endfor -%}
            {%- endmacro %}
            {%- set the_rooms = ['den_thermostat', 'girls_br', 'office'] -%}
            {%- set temps = get_temp(the_rooms).split(",") | reject('eq','') | map('float') | list -%}
            {%- if states.input_select.front_function.state == "mean" -%}
              {{- mean(temps) | round(1) -}}
            {%- elif states.input_select.front_function.state == "max" -%}
              {{- temps | max | round(1) -}}
            {%- elif states.input_select.front_function.state == "min" -%}
              {{- temps | min | round(1) -}}
            {%- else -%}
              Barf
            {%- endif -%}

      front_desired_state:
        friendly_name: Front Desired State
        entity_id:
          - input_select.front_thermostat_mode
          - sensor.front_temps
          - input_number.front_heating_target
          - input_number.front_cooling_target
        value_template: >-
          {% if states.input_select.front_thermostat_mode.state == "heat" -%}
            {% if float(states.sensor.front_temps.state)
                  < float(states.input_number.front_heating_target.state) -%}
              Heating
            {%- else -%}
              Off
            {%- endif %}
          {% elif states.input_select.front_thermostat_mode.state == "cool" -%}
            {% if float(states.sensor.front_temps.state)
                  > float(states.input_number.front_cooling_target.state) -%}
              Cooling
            {%- else -%}
              Off
            {%- endif %}
          {% else %}
            Unknown
          {% endif %}

input_select:
  # --- Front Thermostat Mode dropdown ---
  front_thermostat_mode:
    name: Front Thermostat Mode
    options:
      - "auto"
      - "off"
      - "cool"
      - "heat"
      - "emergency heat"
    icon: mdi:fan

  front_function:
    name: Front Combining Function
    # initial: max
    options:
      - "min"
      - "max"
      - "mean"
    icon: mdi:function

input_number:
  # -- Front Therm targets ---
  front_heating_target:
    name: Front Heating Target
    # initial: 68
    min: 50
    max: 75
    step: 1

  front_cooling_target:
    name: Front Cooling Target
    # initial: 76
    min: 65
    max: 110
    step: 1

input_boolean:
  den_thermostat_occupied:
    name: Den Occupied
    initial: 'on'
    icon: mdi:account
  girls_br_occupied:
    name: Girls Bedroom Occupied
    initial: 'on'
    icon: mdi:account
  office_occupied:
    name: Office Occupied
    initial: 'off'
    icon: mdi:account

group:
  front_thermostat:
    - sensor.front_temps
    - input_select.front_function
    - input_select.front_thermostat_mode
    # - switch.front_thermostat_fan_mode
    - sensor.front_desired_state
    - sensor.den_thermostat_current_state
    - input_number.front_heating_target
    - input_number.front_cooling_target
  front_occupied:
    name: Front Occupied
    control: hidden
    entities:
      - input_boolean.den_thermostat_occupied
      - input_boolean.girls_br_occupied
      - input_boolean.office_occupied

automation:

  # --- Front Thermostat ---
  # Keep mode in sync b/w MQTT/dropdown
  - alias: Set Front Thermostat Mode Selector
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "smartthings/Den Thermostat/thermostatMode"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.front_thermostat_mode
          option: '{{ trigger.payload }}'
  - alias: Set Front Thermostat Mode
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.front_thermostat_mode
      # Might need for this and for setpoint
      # - platform: event
      #   event_type: state_change
      #   event_data:
      #     entity_id: sensor.front_thermostat_current_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: "smartthings/Den Thermostat/thermostatMode"
          payload: '{{ states.input_select.front_thermostat_mode.state }}'
          retain: true

  # Adj Den Thermostat to meet Front Temp (heat)
  - alias: Front Heating Target Set
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_number.front_heating_target
      - platform: state
        entity_id: input_select.front_thermostat_mode
      - platform: state
        entity_id: sensor.front_temps
    condition:
      condition: state
      entity_id: input_select.front_thermostat_mode
      state: 'heat'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.den_heating_target
          value: >-
            {%  set temp = { "observed":   float(states.sensor.front_temps.state),
                             "target":     float(states.input_number.front_heating_target.state),
                             "thermostat": float(states.sensor.den_thermostat_temp.state),
                             "min":        float(states.input_number.den_heating_target.attributes.min),
                             "max":        float(states.input_number.den_heating_target.attributes.max)
                           }  %}
            {% if temp.observed < temp.target - 1 %}            {# ON #}
                {{ [ temp.thermostat + 2, temp.max ] | min }}
            {% elif temp.observed >= temp.target + 1 %}         {# OFF #}
                {{ [ temp.thermostat - 2, temp.min ] | max }}
            {% else %}
                {{ states.input_number.den_heating_target.state | float }}
            {% endif %}
      - service: system_log.write
        data_template:
          message: >-
            Changing den_heating_target to {{ states.input_number.den_heating_target.state }}
          level: info

  # Adj den Thermostat to meet Front Temp (a/c)
  - alias: Front A/C Target Set
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_number.front_cooling_target
      - platform: state
        entity_id: input_select.front_thermostat_mode
      - platform: state
        entity_id: sensor.front_temps
    condition:
      condition: state
      entity_id: input_select.front_thermostat_mode
      state: 'cool'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.den_cooling_target
          value: >-
            {%  set temp = { "observed":   float(states.sensor.front_temps.state),
                             "target":     float(states.input_number.front_cooling_target.state),
                             "thermostat": float(states.sensor.den_thermostat_temp.state),
                             "min":        float(states.input_number.den_cooling_target.attributes.min),
                             "max":        float(states.input_number.den_cooling_target.attributes.max)
                           }  %}
            {% if temp.observed > temp.target + 1 %}            {# ON #}
                {{ [ temp.thermostat - 2, temp.min ] | max }}
            {% elif temp.observed <= temp.target - 1 %}         {# OFF #}
                {{ [ temp.thermostat + 2, temp.max ] | min }}
            {% else %}
                {{ states.input_number.den_cooling_target.state | float }}
            {% endif %}
      - service: system_log.write
        data_template:
          message: >-
            Changing den_cooling_target to {{ states.input_number.den_cooling_target.state }}
          level: info

  # Create a virtual climate.mqtt sensor for Front

  # From virtual therm to mqtt
  - alias: Front temperature vTherm to climate.MQTT
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: sensor.front_temps
    action:
      - service: mqtt.publish
        data_template:
          topic: "climate/Front vThermostat/temperature"
          payload: '{{ states.sensor.front_temps.state }}'
          retain: true
  - alias: Front thermostatMode vTherm to climate.MQTT
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_select.front_thermostat_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: "climate/Front vThermostat/thermostatMode"
          payload: >-
            {% set values = { 'heating':'heat',  'cooling':'cool' } %}
            {{ values[ trigger.to_state.state ] if value in values.keys() else trigger.to_state.state }}
          retain: true
  - alias: Front setpoint vTherm to climate.MQTT
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_number.front_heating_target
      # - platform: state
      #   entity_id: input_number.front_cooling_target
    action:
      - service: mqtt.publish
        data_template:
          topic: "climate/Front vThermostat/thermostatSetpoint"
          # TODO: report cooling_target if we are cooling
          # payload: '{{ states.input_number.front_heating_target.state }}'
          payload: >-
            {{ trigger.to_state.state }}
          retain: true
      - service: system_log.write
        data_template:
          message: >-
            Changing posting mqtt/front/thermostatSetpoint to  {{ trigger.to_state.state }}
          level: info

  # From climate.mqtt to virtual therm
  - alias: Front thermostatMode climate.MQTT to vTherm
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: mqtt
        topic: "climate/Front vThermostat/thermostatMode"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.front_thermostat_mode
          value: >-
            {% set values = { 'heat':'heating',  'cool':'cooling' } %}
            {{ values[ trigger.to_state.state ] if value in values.keys() else trigger.to_state.state }}
      - service: system_log.write
        data_template:
          message: >-
            {% set values = { 'heat':'heating', 'emergency heat': 'heat', 'cool':'cooling' } %}
            Changing front_thermostate_mode to
            {{ values[ trigger.payload ] if value in values.keys() else trigger.payload }}
          level: info
  - alias: Front setpoint climate.MQTT to vTherm
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: mqtt
        topic: "climate/Front vThermostat/thermostatSetpoint"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.front_heating_target
          value: >-
            {{ trigger.payload }}
      - service: system_log.write
        data_template:
          message: >-
            Changing front_heating_target to {{ trigger.payload }}
          level: info

    # mode_command_template: >-
    #         {% set values = { 'auto':'auto', 'heat':'heating',  'cool':'cooling', 'off':'off'} %}
    #         {{ values[value] if value in values.keys() else 'off' }}

    # - input_select.front_function
    # # - switch.front_thermostat_fan_mode
    # - sensor.front_desired_state
    # - sensor.den_thermostat_current_state
