homeassistant:
  customize:
    group.rear_thermostat:
      friendly_name: 'Rear Temps/Thermostat'
      icon: mdi:fan
    sensor.rear_temps:
      icon: mdi:thermometer
    input_select.rear_function:
      persistent: true
    input_number.rear_heating_target:
      persistent: true
    input_number.rear_cooling_target:
      persistent: true

sensor:
  - platform: template
    sensors:
      rear_temps:
        friendly_name: "Rear Temps"
        unit_of_measurement: '°F'
        entity_id:
          - sensor.kitchen_thermostat_temp
          - sensor.mbr_temp
          # - sensor.basement_temp
          - input_boolean.kitchen_thermostat_occupied
          - input_boolean.mbr_occupied
          - input_boolean.basement_occupied
          - input_select.rear_function
        value_template: >-
            {% macro mean(values) -%}
               {{- (values|sum) / (values|length) -}}
            {%- endmacro %}
            {% macro get_temp(rooms) -%}
              {% for room in rooms -%}
                {%- if states.input_boolean[room ~ "_occupied"].state == "on" -%}
                  {{-states.sensor[room ~ "_temp"].state-}},
                {%- endif -%}
              {%- endfor -%}
            {%- endmacro %}
            {%- set the_rooms = ['mbr', 'kitchen_thermostat', 'basement'] -%}
            {%- set temps = get_temp(the_rooms).split(",") | reject('eq','') | map('float') | list -%}
            {%- if states.input_select.rear_function.state == "mean" -%}
              {{- mean(temps) | round(1) -}}
            {%- elif states.input_select.rear_function.state == "max" -%}
              {{- temps | max | round(1) -}}
            {%- elif states.input_select.rear_function.state == "min" -%}
              {{- temps | min | round(1) -}}
            {%- else -%}
              Barf
            {%- endif -%}

      rear_desired_state:
        friendly_name: Rear Desired State
        entity_id:
          - input_select.rear_thermostat_mode
          - sensor.rear_temps
          - input_number.rear_heating_target
          - input_number.rear_cooling_target
        value_template: >-
          {% if states.input_select.rear_thermostat_mode.state == "heat" -%}
            {% if float(states.sensor.rear_temps.state)
                  < float(states.input_number.rear_heating_target.state) -%}
              Heating
            {%- else -%}
              Off
            {%- endif %}
          {% elif states.input_select.rear_thermostat_mode.state == "cool" -%}
            {% if float(states.sensor.rear_temps.state)
                  > float(states.input_number.rear_cooling_target.state) -%}
              Cooling
            {%- else -%}
              Off
            {%- endif %}
          {% else %}
            Unknown
          {% endif %}

input_select:
  # --- Rear Thermostate Mode dropdown ---
  rear_thermostat_mode:
    name: Rear Thermostat Mode
    options:
      - "auto"
      - "off"
      - "cool"
      - "heat"
      - "emergency heat"
    icon: mdi:fan

  rear_function:
    name: Rear Combining Function
    # initial: max
    options:
      - "min"
      - "max"
      - "mean"
    icon: mdi:function

input_number:
  # -- Rear Therm targets ---
  rear_heating_target:
    name: Rear Heating Target
    # initial: 68
    min: 50
    max: 75
    step: 1

  rear_cooling_target:
    name: Rear Cooling Target
    # initial: 76
    min: 65
    max: 110
    step: 1

input_boolean:
  kitchen_thermostat_occupied:
    name: Kitchen Occupied
    initial: 'on'
    icon: mdi:account
  mbr_occupied:
    name: Master Bedroom Occupied
    initial: 'on'
    icon: mdi:account
  basement_occupied:
    name: Basement Occupied
    initial: 'off'
    icon: mdi:account

group:
  rear_thermostat:
    - sensor.rear_temps
    - input_select.rear_function
    - input_select.rear_thermostat_mode
    # - switch.rear_thermostat_fan_mode
    - sensor.rear_desired_state
    - sensor.kitchen_thermostat_current_state
    - input_number.rear_heating_target
    - input_number.rear_cooling_target
  rear_occupied:
    name: Rear Occupied
    control: hidden
    entities:
      - input_boolean.kitchen_thermostat_occupied
      - input_boolean.mbr_occupied
      - input_boolean.basement_occupied

automation:

  # --- Rear Thermostat ---
  # Keep mode in sync b/w MQTT/dropdown
  - alias: Set Rear Thermostat Mode Selector
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "smartthings/Kitchen Thermostat/thermostatMode"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.rear_thermostat_mode
          option: '{{ trigger.payload }}'
  - alias: Set Rear Thermostat Mode
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.rear_thermostat_mode
      # Might need for this and for setpoint
      # - platform: event
      #   event_type: state_change
      #   event_data:
      #     entity_id: sensor.rear_thermostat_current_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: "smartthings/Kitchen Thermostat/thermostatMode"
          payload: '{{ states.input_select.rear_thermostat_mode.state }}'
          retain: true

  # Adj Kitchen Thermostat to meet Rear Temp (heat)
  - alias: Rear Heating Target Set
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_number.rear_heating_target
      - platform: state
        entity_id: input_select.rear_thermostat_mode
      - platform: state
        entity_id: sensor.rear_temps
    condition:
      condition: state
      entity_id: input_select.rear_thermostat_mode
      state: 'heat'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.kitchen_heating_target
          value: >-
            {%  set temp = { "observed":   float(states.sensor.rear_temps.state),
                             "target":     float(states.input_number.rear_heating_target.state),
                             "thermostat": float(states.sensor.kitchen_thermostat_temp.state),
                             "min":        float(states.input_number.kitchen_heating_target.attributes.min),
                             "max":        float(states.input_number.kitchen_heating_target.attributes.max)
                           }  %}
            {% if temp.observed < temp.target - 1 %}          {# ON #}
                {{ [ temp.thermostat + 2, temp.max ] | min }}
            {% elif temp.observed >= temp.target + 1 %}       {# OFF #}
                {{ [ temp.thermostat - 2, temp.min ] | max }}
            {% else %}
                {{ states.input_number.kitchen_heating_target.state | float }}
            {% endif %}
      - service: system_log.write
        data_template:
          message: >-
            Changing kitchen_heating_target to {{ states.input_number.kitchen_heating_target.state }}
          level: info

  # Adj Kitchen Thermostat to meet Rear Temp (a/c)
  - alias: Rear A/C Target Set
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_number.rear_cooling_target
      - platform: state
        entity_id: input_select.rear_thermostat_mode
      - platform: state
        entity_id: sensor.rear_temps
    condition:
      condition: state
      entity_id: input_select.rear_thermostat_mode
      state: 'cool'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.kitchen_cooling_target
          value: >-
            {%  set temp = { "observed":   float(states.sensor.rear_temps.state),
                             "target":     float(states.input_number.rear_cooling_target.state),
                             "thermostat": float(states.sensor.kitchen_thermostat_temp.state),
                             "min":        float(states.input_number.kitchen_cooling_target.attributes.min),
                             "max":        float(states.input_number.kitchen_cooling_target.attributes.max)
                           }  %}
            {% if temp.observed > temp.target + 1 %}          {# ON #}
                {{ [ temp.thermostat - 2, temp.min ] | max }}
            {% elif temp.observed <= temp.target - 1 %}       {# OFF #}
                {{ [ temp.thermostat + 2, temp.max ] | min }}
            {% else %}
                {{ states.input_number.kitchen_cooling_target.state | float }}
            {% endif %}
      - service: system_log.write
        data_template:
          message: >-
            Changing kitchen_cooling_target to {{ states.input_number.kitchen_cooling_target.state }}
          level: info

  # Create a virtual climate.mqtt sensor for Front

  # From virtual therm to mqtt
  - alias: Rear vTherm temperature to MQTT
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: sensor.rear_temps
    action:
      - service: mqtt.publish
        data_template:
          topic: "climate/Rear vThermostat/temperature"
          payload: '{{ states.sensor.rear_temps.state }}'
          retain: true
  - alias: Rear vTherm thermostateMode to MQTT
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_select.rear_thermostat_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: "climate/Rear vThermostat/thermostatMode"
          payload: >-
            {% set values = { 'heating':'heat',  'cooling':'cool' } %}
            {{ values[ trigger.to_state.state ] if value in values.keys() else trigger.to_state.state }}
          retain: true
  - alias: Rear vTherm setpoint to MQTT
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_number.rear_heating_target
      - platform: state
        entity_id: input_number.rear_cooling_target
    action:
      - service: mqtt.publish
        data_template:
          topic: "climate/Rear vThermostat/thermostatSetpoint"
          # TODO: report cooling_target if we are cooling
          # payload: '{{ states.input_number.rear_heating_target.state }}'
          payload: >-
            {{ trigger.to_state.state }}
          retain: true

  # From mqtt to virtual therm
  - alias: Rear thermostatMode climate.MQTT to vTherm
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: mqtt
        topic: "climate/Rear vThermostat/thermostatMode"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.rear_thermostat_mode
          value: >-
            {% set values = { 'heat':'heating', 'emergency heat': 'heat', 'cool':'cooling' } %}
            {{ values[ trigger.payload ] if value in values.keys() else trigger.payload }}
      - service: system_log.write
        data_template:
          message: >-
            {% set values = { 'heat':'heating',  'cool':'cooling' } %}
            Changing rear_thermostate_mode to
            {{ values[ trigger.payload ] if value in values.keys() else trigger.payload }}
          level: info
  - alias: Rear setpoint climate.MQTT to vTherm
    hide_entity: true
    initial_state: "on"
    trigger:
      - platform: mqtt
        topic: "climate/Rear vThermostat/thermostatSetpoint"
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.rear_heating_target
          value: >-
            {{ trigger.payload }}
      - service: system_log.write
        data_template:
          message: >-
            Changing rear_heating_target to {{ trigger.payload }}
          level: info


    # mode_command_template: >-
    #         {% set values = { 'auto':'auto', 'heat':'heating',  'cool':'cooling', 'off':'off'} %}
    #         {{ values[value] if value in values.keys() else 'off' }}

    # - input_select.rear_function
    # # - switch.rear_thermostat_fan_mode
    # - sensor.rear_desired_state
    # - sensor.den_thermostat_current_state
