group:
  sensornode_porch_card:
    name: Porch Sensor
    entities:
      - sensor.porch_temperature
      - sensor.porch_humidity
      - sensor.porch_ldr
      - sensor.porch_pir
      - sensor.porch_real_feel
      - light.porch_led

sensor:
  - platform: mqtt
    state_topic: "hass/sensor-porch"
    name: "Porch Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "hass/sensor-porch"
    name: "Porch LDR"
    # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "hass/sensor-porch"
    name: "Porch PIR"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "hass/sensor-porch"
    name: "Porch Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "hass/sensor-porch"
    name: "Porch Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'
