#

homeassistant:

group:
  locks:
    name: Lock
    entities:
      - lock.sidedoor
      - sensor.sidedoor_alarm_level
      - sensor.sidedoor_alarm_type
      - sensor.sidedoor_action
      - sensor.sidedoor_code

#  door_lock_batteries:
#    name: Door Locks
#    entities:
#      - sensor.door_lock_batteries_4thbedroom_door
#      - sensor.door_lock_batteries_front_door
#      - sensor.door_lock_batteries_garageside_door
#      - sensor.door_lock_batteries_rear_door
#  lock_status:
#    name: Lock Status
#    entities:
#      - zwave.lock.4thbedroom_door
#      - zwave.lock.front_door
#      - zwave.lock.garageside_door
#      - zwave.lock.rear_door

# sensor:
#   - platform: template
#     sensors:
