#

homeassistant:

group:
  locks:
    name: Lock
    entities:
      - lock.sidedoor
      - sensor.sidedoor_alarm_level
      - sensor.sidedoor_alarm_type
      - sensor.sidedoor_action
      - sensor.sidedoor_code

#  door_lock_batteries:
#    name: Door Locks
#    entities:
#      - sensor.door_lock_batteries_4thbedroom_door
#      - sensor.door_lock_batteries_front_door
#      - sensor.door_lock_batteries_garageside_door
#      - sensor.door_lock_batteries_rear_door
#  lock_status:
#    name: Lock Status
#    entities:
#      - zwave.lock.4thbedroom_door
#      - zwave.lock.front_door
#      - zwave.lock.garageside_door
#      - zwave.lock.rear_door

sensor:
  - platform: template
    sensors:
      sidedoor_action:
        friendly_name: 'Side Door Action'
        value_template: >
          {% if is_state('sensor.sidedoor_alarm_type', '22') %}
            Manual Unlock
          {% elif is_state('sensor.sidedoor_alarm_type', '21') %}
            Manual Lock
          {% elif is_state('sensor.sidedoor_alarm_type', '19') %}
            Keypad Unlock
          {% elif is_state('sensor.sidedoor_alarm_type', '18') %}
            Keypad Lock
          {% elif is_state('sensor.sidedoor_alarm_type', '25') %}
            Wireless Unlock
          {% elif is_state('sensor.sidedoor_alarm_type', '24') %}
            Wireless Lock
          {% elif is_state('sensor.sidedoor_alarm_type', '9') %}
            Lock Jammed
          {% elif is_state('sensor.sidedoor_alarm_type', '161') %}
            Tamper Alarm
          {% else %}
            Other {{ sensor.sidedoor_alarm_type }}
          {% endif %}
    sidedoor_code:
      friendly_name: 'Side Door Code'
      value_template: >
        {% if is_state('sensor.sidedoor_alarm_type', '19') or is_state('sensor.sidedoor_alarm_type', '18') %}
          {% if is_state('sensor.sidedoor_alarm_level', '1') %}
            User1
          {% elif is_state('sensor.sidedoor_alarm_level', '2') %}
            User2
          {% elif is_state('sensor.sidedoor_alarm_level', '3') %}
            User3
          {% elif is_state('sensor.sidedoor_alarm_level', '4') %}
            User4
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}

#      door_lock_batteries_fourth_bedroom_door:
#        value_template: '{{states["zwave"]["lock_4thbedroom_door"]["attributes"]["battery_level"]}}'
#        friendly_name: Fourth Bedroom
#        unit_of_measurement: '%'
#        icon_template: >-
#          {% set level = ((states["zwave"]["lock_4thbedroom_door"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
#            mdi:battery
#          {%- if level > 90 -%}
#
#          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
#            -{{ level }}
#          {%- elif level > 50 -%}
#            -60
#          {%- elif level > 30 -%}
#            -40
#          {%- else -%}
#            -alert
#          {%- endif -%}
#
#      door_lock_batteries_front_door:
#        value_template: '{{states["zwave"]["lock_front_door"]["attributes"]["battery_level"]}}'
#        friendly_name: Front Door
#        unit_of_measurement: '%'
#        icon_template: >-
#          {% set level = ((states["zwave"]["lock_front_door"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
#            mdi:battery
#          {%- if level > 90 -%}
#
#          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
#            -{{ level }}
#          {%- elif level > 50 -%}
#            -60
#          {%- elif level > 30 -%}
#            -40
#          {%- else -%}
#            -alert
#          {%- endif -%}
#
#      door_lock_batteries_garageside_door:
#        value_template: '{{states["zwave"]["lock_garageside_door"]["attributes"]["battery_level"]}}'
#        friendly_name: Garage Side Door
#        unit_of_measurement: '%'
#        icon_template: >-
#          {% set level = ((states["zwave"]["lock_garageside_door"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
#            mdi:battery
#          {%- if level > 90 -%}
#
#          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
#            -{{ level }}
#          {%- elif level > 50 -%}
#            -60
#          {%- elif level > 30 -%}
#            -40
#          {%- else -%}
#            -alert
#          {%- endif -%}
#
#      door_lock_batteries_rear_door:
#        value_template: '{{states["zwave"]["lock_rear_door"]["attributes"]["battery_level"]}}'
#        friendly_name: Rear Door
#        unit_of_measurement: '%'
#        icon_template: >-
#          {% set level = ((states["zwave"]["lock_rear_door"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
#            mdi:battery
#          {%- if level > 90 -%}
#
#          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
#            -{{ level }}
#          {%- elif level > 50 -%}
#            -60
#          {%- elif level > 30 -%}
#            -40
#          {%- else -%}
#            -alert
#          {%- endif -%}
