- platform: mqtt
  state_topic: "hass/sensor-master"
  name: "Master Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-master"
  name: "Master LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-master"
  name: "Master PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-master"
  name: "Master Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-master"
  name: "Master Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-kitchen"
  name: "Kitchen Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-kitchen"
  name: "Kitchen LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-kitchen"
  name: "Kitchen PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-kitchen"
  name: "Kitchen Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-kitchen"
  name: "Kitchen Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-basement"
  name: "Basement Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-basement"
  name: "Basement LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-basement"
  name: "Basement PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-basement"
  name: "Basement Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-basement"
  name: "Basement Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-thirdfloor"
  name: "Third Flr Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-thirdfloor"
  name: "Third Flr LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-thirdfloor"
  name: "Third Flr PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-thirdfloor"
  name: "Third Flr Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-thirdfloor"
  name: "Third Flr Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-bedrooms"
  name: "Bedrooms Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-bedrooms"
  name: "Bedrooms LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-bedrooms"
  name: "Bedrooms PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-bedrooms"
  name: "Bedrooms Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-bedrooms"
  name: "Bedrooms Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-porch"
  name: "Porch Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-porch"
  name: "Porch LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-porch"
  name: "Porch PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-porch"
  name: "Porch Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-porch"
  name: "Porch Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'
