- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom LDR"
  # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"
  value_template: '{{ value_json.ldr }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom PIR"
  value_template: '{{ value_json.motion }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Temperature"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'

- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Real Feel"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'

# Light switch
# XXXX: Should this be in binary_sensor?
- platform: mqtt
  state_topic: "hass/sensor-livingroom"
  name: "LivingRoom Button"
  # device_class:
  value_template: '{{ value_json.button }}'
