- alias: Basement steps switch turns on all lights
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - switch.basement_step_lights
      # - switch.basement_lights
    to: "on"
  action:
    service: switch.turn_on
    entity_id:
      # - group.basement_lights
      - switch.basement_lights

- alias: Basement steps switch turns off all lights
  initial_state: 'on'
  trigger:
    platform: state
    entity_id:
      - switch.basement_step_lights
      # - switch.basement_lights
    to: "off"
  action:
    service: switch.turn_off
    entity_id:
      # - group.basement_lights
      - switch.basement_lights
