- alias: Notify CallerID
  trigger:
    platform: state
    entity_id: sensor.modem_callerid
    to: "callerid"
  action:
    service: notify.pushover
    data:
      message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} at {{ states.sensor.modem_callerid.attributes.cid_number }} '

- alias: Notify CallerID webui
  trigger:
    platform: state
    entity_id: sensor.modem_callerid
    to: "callerid"
  action:
    service: persistent_notification.create
    data:
      title: "Call from"
      message: '{{ states.sensor.modem_callerid.attributes.cid_time.strftime("%I:%M %p") }} {{ states.sensor.modem_callerid.attributes.cid_name }}  {{ states.sensor.modem_callerid.attributes.cid_number }} '

- alias: Say CallerID
  trigger:
    platform: state
    entity_id: sensor.modem_callerid
    to: "callerid"
  action:
    service: mqtt.publish
    data:
      topic: 'hass/callerid/say'
      payload_template: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} '

# - alias: Say CallerID
#   trigger:
#     platform: state
#     entity_id: sensor.modem_callerid
#     to: "callerid"
#   action:
#     service: tts.google_say
#     entity_id: media_player.lms
#     data_template:
#       message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} '
