- alias: Turn on family room lights
  trigger:
    platform: state
    entity_id: sensor.livingroom_pir
    to: "motion detected"
  condition:
    - condition: numeric_state
      entity_id: sensor.livingroom_ldr
      below: 500
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.livingroom_button.last_updated) | int > 60 }}'
    # - condition: template
    #   value_template: '{{ states.sensor.livingroom_ldr.state | float < 500 }}'
  action:
    service: switch.turn_on
    entity_id:
      - group.family_room

- alias: Turn off family room lights
  trigger:
    - platform: state
      entity_id: sensor.livingroom_pir
      to: "standby"
      for:
        minutes: 15
  condition:
    - condition: template
      value_template: '{{ as_timestamp(now()) - as_timestamp(states.sensor.livingroom_button.last_updated) | int > 60 }}'
  #   - condition: time
  #     after: '21:00:00'
  action:
    service: switch.turn_off
    entity_id:
      - group.family_room

- alias: Toggle family room lights
  trigger:
    platform: state
    entity_id: sensor.livingroom_button
    # to: "ON"
    # to: "OFF"
  action:
    service: switch.toggle
    entity_id:
      - group.family_room
