- alias: Turn on porch light at sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:30
  action:
    service: switch.turn_on
    entity_id:
      - switch.front_porch_lights_switch

- alias: Turn off porch light at sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: +00:30
  action:
    service: switch.turn_off
    entity_id:
      - switch.front_porch_lights_switch

- alias: Turn on trim lights
  trigger:
    platform: time
    at: '14:00:00'
  action:
    service: switch.turn_on
    entity_id:
      - switch.exteriorlights_switch

- alias: Turn off trim lights
  trigger:
    platform: time
    at: '8:20:00'
  action:
    service: switch.turn_off
    entity_id:
      - switch.exteriorlights_switch
