# -------------------------------------------
homeassistant:
  customize:
    group.sprinkler_automation01:
      control: hidden
    input_boolean.sprinkler01_scheduled:
      persistent: true
    input_datetime.sprinkler01_time:
      persistent: true
  customize_glob:
    "input_boolean.sprinkler01_*day":
      persistent: true
    "input_number.sprinkler01_sch_zone_*":
      persistent: true

group:
  sprinkler_automation01:
    name: Sprinkler Automation 01
    entities:
      - input_boolean.sprinkler01_scheduled
      - input_datetime.sprinkler01_time
      - input_boolean.sprinkler01_monday
      - input_boolean.sprinkler01_tuesday
      - input_boolean.sprinkler01_wednesday
      - input_boolean.sprinkler01_thrusday
      - input_boolean.sprinkler01_friday
      - input_boolean.sprinkler01_saturday
      - input_boolean.sprinkler01_sunday
      - input_number.sprinkler01_sch_zone_1
      - input_number.sprinkler01_sch_zone_2
      - input_number.sprinkler01_sch_zone_3
      - input_number.sprinkler01_sch_zone_4
      - input_number.sprinkler01_sch_zone_5
      - input_number.sprinkler01_sch_zone_6
      - input_number.sprinkler01_sch_zone_7
      - input_number.sprinkler01_sch_zone_8
      - binary_sensor.rain_expected

input_boolean:
  sprinkler01_scheduled:
    name: Sprinkler Scheduled
    icon: mdi:alarm
  sprinkler01_monday:
    name: Mon
    icon: mdi:calendar
  sprinkler01_tuesday:
    name: Tues
    icon: mdi:calendar
  sprinkler01_wednesday:
    name: Wed
    icon: mdi:calendar
  sprinkler01_thrusday:
    name: Thur
    icon: mdi:calendar
  sprinkler01_friday:
    name: Fri
    icon: mdi:calendar
  sprinkler01_saturday:
    name: Sat
    icon: mdi:calendar
  sprinkler01_sunday:
    name: Sun
    icon: mdi:calendar

input_datetime:
  sprinkler01_time:
    name: Sprinkler Start
    has_date: false
    has_time: true

input_number:
  sprinkler01_sch_zone_1:
    name: Front Bushes
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_2:
    name: Front Lawn
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_3:
    name: Back Bushes
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_4:
    name: Back Lawn
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_5:
    name: Back Fence
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_6:
    name: Flower Boxes
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_7:
    name: Zone 7
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'
  sprinkler01_sch_zone_8:
    name: Zone 8
    # initial: 10
    min: 0
    max: 40
    step: 1
    unit_of_measurement: 'min'

automation:
  - alias: 'Sprinkler schedule'
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.input_datetime.sprinkler01_time.state == states.sensor.time.state + ":00" }}'
    condition:
      - condition: state
        entity_id: input_boolean.sprinkler01_scheduled
        state: 'on'
      - condition: template
        value_template: >
          {{
            ( ( is_state("sensor.clock_day","Monday") and states("input_boolean.sprinkler01_monday") ) or
              ( is_state("sensor.clock_day","Tuesday") and states("input_boolean.sprinkler01_tuesday") ) or
              ( is_state("sensor.clock_day","Wednesday") and states("input_boolean.sprinkler01_wednesday") ) or
              ( is_state("sensor.clock_day","Thursday") and states("input_boolean.sprinkler01_thrusday") ) or
              ( is_state("sensor.clock_day","Friday") and states("input_boolean.sprinkler01_friday") ) or
              ( is_state("sensor.clock_day","Saturday") and states("input_boolean.sprinkler01_saturday") ) or
              ( is_state("sensor.clock_day","Sunday") and states("input_boolean.sprinkler01_sunday") )
            ) == "on"
          }}
      - condition: state
        entity_id: binary_sensor.rain_expected
        state: 'off'
    action:
      - service: mqtt.publish
        data_template:
          topic: "hass/sprinkler01/set"
          payload: >
            { "on": true, "zones": [
              { "id": 1, "dur": {{ states.input_number.sprinkler01_sch_zone_1.state | int }} },
              { "id": 2, "dur": {{ states.input_number.sprinkler01_sch_zone_2.state | int }} },
              { "id": 3, "dur": {{ states.input_number.sprinkler01_sch_zone_3.state | int }} },
              { "id": 4, "dur": {{ states.input_number.sprinkler01_sch_zone_4.state | int }} },
              { "id": 5, "dur": {{ states.input_number.sprinkler01_sch_zone_5.state | int }} },
              { "id": 6, "dur": {{ states.input_number.sprinkler01_sch_zone_6.state | int }} },
              { "id": 7, "dur": {{ states.input_number.sprinkler01_sch_zone_7.state | int }} },
              { "id": 8, "dur": {{ states.input_number.sprinkler01_sch_zone_8.state | int }} }
            ] }
          retain: false
      # - condition: state
      #   entity_id: input_boolean.debug_mode
      #   state: 'on'
      - service: notify.pushover
        data_template:
          title: 'HA Sprinkler'
          message: |
            [Sprinkler]
            Starting sprinkler
            1: {{ states.input_number.sprinkler01_sch_zone_1.state | int }} mins
            2: {{ states.input_number.sprinkler01_sch_zone_2.state | int }} mins
            3: {{ states.input_number.sprinkler01_sch_zone_3.state | int }} mins
            4: {{ states.input_number.sprinkler01_sch_zone_4.state | int }} mins
            5: {{ states.input_number.sprinkler01_sch_zone_5.state | int }} mins
            6: {{ states.input_number.sprinkler01_sch_zone_6.state | int }} mins
            7: {{ states.input_number.sprinkler01_sch_zone_7.state | int }} mins
            8: {{ states.input_number.sprinkler01_sch_zone_8.state | int }} mins
  - alias: 'Sprinkler skip notify'
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: '{{ states.input_datetime.sprinkler01_time.state == states.sensor.time.state + ":00" }}'
    condition:
      - condition: state
        entity_id: input_boolean.sprinkler01_scheduled
        state: 'on'
      - condition: template
        value_template: >
          {{
            ( ( is_state("sensor.clock_day","Monday") and states("input_boolean.sprinkler01_monday") ) or
              ( is_state("sensor.clock_day","Tuesday") and states("input_boolean.sprinkler01_tuesday") ) or
              ( is_state("sensor.clock_day","Wednesday") and states("input_boolean.sprinkler01_wednesday") ) or
              ( is_state("sensor.clock_day","Thursday") and states("input_boolean.sprinkler01_thrusday") ) or
              ( is_state("sensor.clock_day","Friday") and states("input_boolean.sprinkler01_friday") ) or
              ( is_state("sensor.clock_day","Saturday") and states("input_boolean.sprinkler01_saturday") ) or
              ( is_state("sensor.clock_day","Sunday") and states("input_boolean.sprinkler01_sunday") )
            ) == "on"
          }}
      - condition: state
        entity_id: binary_sensor.rain_expected
        state: 'on'
    action:
      - service: notify.pushover
        data_template:
          title: 'HA Sprinkler'
          message: |
            [Sprinkler]
            Skiping watering due to expected rain.
