# -------------------------------------------
#  Caller ID Routines
#  Uses USB Modem to monitor incoming calls
# -------------------------------------------

homeassistant:

sensor:
  - platform: modem_callerid
    devide: /dev/ttyACM0

shell_command:
  notify_if_known: '/srv/app/hass/config/bin/notify-if-known.sh -n "{{ states.sensor.modem_callerid.attributes.cid_name }}" -p "{{ states.sensor.modem_callerid.attributes.cid_number }} -m {{ mqtt_pw }} -H {{ http_pw }}"'

group:
  phone:
    name: Phone
    entities:
      - sensor.modem_callerid

automation:
  - alias: Notify CallerID
    initial_state: 'off'
    trigger:
      platform: state
      entity_id: sensor.modem_callerid
      to: "callerid"
    action:
      service: notify.pushover
      data:
        message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} at {{ states.sensor.modem_callerid.attributes.cid_number }} '

  - alias: Notify CallerID webui
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.modem_callerid
      to: "callerid"
    action:
      service: persistent_notification.create
      data:
        title: "Call from"
        message: '{{ states.sensor.modem_callerid.attributes.cid_time.strftime("%I:%M %p") }} {{ states.sensor.modem_callerid.attributes.cid_name }}  {{ states.sensor.modem_callerid.attributes.cid_number }} '

  - alias: Say CallerID
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.modem_callerid
      to: "callerid"
    action:
      service: shell_command.notify_if_known
      data:
        http_pw: !secret http_api_password
        mqtt_pw: !secret mqtt_password

  # Disable voice annoucements
  #   - Don't like the TTS on rPi
  #   - Too hard to understand the name
  #   - Using lms stops music and doesn't restart

  # - alias: Say CallerID
  #   trigger:
  #     platform: state
  #     entity_id: sensor.modem_callerid
  #     to: "callerid"
  #   action:
  #     service: mqtt.publish
  #     data:
  #       topic: 'hass/mqtt-say/message'
  #       payload_template: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} '

  # - alias: Say CallerID
  #   trigger:
  #     platform: state
  #     entity_id: sensor.modem_callerid
  #     to: "callerid"
  #   action:
  #     service: tts.google_say
  #     entity_id: media_player.lms
  #     data_template:
  #       message: 'Call from {{ states.sensor.modem_callerid.attributes.cid_name }} '
