# -------------------------------------------
#  Clean data for the Floorplan UI.
# -------------------------------------------
#
homeassistant:
  customize_glob:

    "sensor.clock_*":
      hidden: true
      homebridge_hidden: true

group:
  date_time:
    name: Date/Time
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time

# ---Sensor for Time and Date.-----------------------------
sensor:

  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'

  - platform: template
    sensors:
      clock_time:
        friendly_name: 'Clock Time'
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}}
        entity_id:
          - sensor.time

  - platform: template
    scan_interval: 30000
    sensors:
      clock_am_pm:
        friendly_name: 'AM/PM'
        value_template: >-
          {{now().strftime("%p")}}
        entity_id:
          - sensor.time
      clock_day:
        friendly_name: 'Day'
        value_template: >-
          {{now().strftime("%A")}}
        entity_id:
          - sensor.date
      clock_date:
        friendly_name: 'Clock Date'
        value_template: >-
          {{now().strftime("%B")}} {{now().strftime("%d")}}, {{now().year}}
        entity_id:
          - sensor.date
      clock_dom:
        friendly_name: 'Clock DOM'
        value_template: >-
          {{now().strftime("%e")}}
        entity_id:
          - sensor.date
