automation:
  - alias: Annouce HA Restarted
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: script.announce_ha_start

script:
  announce_ha_start:
    alias: Announce HA Restarted
    sequence:
      - service: notify.mqtt_say
        data:
          message: "Home Assistant restarted"
