
homeassistant:
  customize:
    sensor.sp500:
      friendly_name: 'S&P 500'
      custom_ui_state_card: state-card-custom-ui
      extra_data_template: 
        - '${attributes.priceChangePercent}%'
        - 'last updated ${attributes.quoteTime}'
      templates:
        theme: >
          if (attributes.priceChangePercent > 0) return 'green'; else return 'red';
    sensor.bitcoin:
      friendly_name: 'Bitcoin'
      custom_ui_state_card: state-card-custom-ui
      extra_data_template: 
        - '${attributes.priceChangePercent}%'
        - 'last updated ${attributes.quoteTime}'
      templates:
        theme: >
          if (attributes.priceChangePercent > 0) return 'green'; else return 'red';

group:
  finance:
    name: Finance
    entities:
      - sensor.sp500
      - sensor.bitcoin

sensor:
  - platform: mqtt
    state_topic: 'hass/stock-price/SPY'
    name: SP500
    unit_of_measurement: '$'
    value_template: '{{ value_json.price }}'
    json_attributes:
      - name
      - priceChangePercent
      - quoteTime

  - platform: mqtt
    state_topic: 'hass/stock-price/BTC='
    name: Bitcoin
    unit_of_measurement: '$'
    value_template: '{{ value_json.price }}'
    json_attributes:
      - name
      - priceChangePercent
      - quoteTime

