#

homeassistant:
  customize:
    sensor.mean_rate:
      friendly_name: Mean Hash Rate (30m)
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true

    switch.restart_miner:
      friendly_name: Restart Miner
      custom_ui_state_card: state-card-custom-ui
      confirm_controls_show_lock: true

group:
  miner:
    name: Miner
    entities:
      - sensor.mean_rate
      - switch.miner_power
      - switch.restart_miner

shell_command:
  restart_miner: '/srv/app/hass/config/bin/restart-miner.sh'

# Don't really need the script anymore, but keeping in case we want to
# add more steps to the sequence
script:
  restart_miner:
    sequence:
      - service: shell_command.restart_miner

# Create a switch just so we can use custom-ui confirm
switch:
  - platform: template
    switches:
      restart_miner:
        value_template: "{{ false }}"
        turn_on:
          service: script.restart_miner
        turn_off:

sensor:
  platform: influxdb
  host: pip
  queries:
    - name: mean rate
      unit_of_measurement: "GH/s"
      where: 'time > now() - 30m'
      measurement: miner_rate
      field: value
      group_function: mean
      database: home_assistant
      value_template: '{{ value | round(1) }}'
