homeassistant:
  # customize:

media_player:
  - platform: squeezebox
    name: lms
    # host: 127.0.0.1
    host: 192.168.1.201
    port: 9001

# media_player:
#    - platform: cast

group:
  music:
    name: Music
    entities:
      - media_player.kitchen
      - media_player.outside
      - media_player.livingroom
      - media_player.porch
      - media_player.mbr

# automations:

intent_script:
  SkipSongIntent:
    speech:
      text: >
        Ok. Skipping to next track in kitchen.
    async_action: true
    action:
      service: media_player.media_next_track
      entity_id: media_player.kitchen
  PlaySongIntent:
    speech:
      text: >
        Ok. Playing music in kitchen.
    async_action: true
    action:
      service: media_player.media_play
      entity_id: media_player.kitchen
  StopStongIntent:
    speech:
      text: >
        Ok. Stopping music in kitchen.
    async_action: true
    action:
      service: media_player.media_stop
      entity_id: media_player.kitchen
  ChangePlaylistIntent:
    speech:
      text: >
        Ok. Playing {Playlist} in kitchen.
    async_action: true
    action:
      service: media_player.play_media
      entity_id: media_player.kitchen
      data:
        media_content_id: >
          {% if   Playlist.lower(), 'jazz' %} pandora://3141420448449849928.mp3
          {% elif Playlist.lower(), "van morrison" %} pandora://3374695489688595016.mp3
          {% elif Playlist.lower(), 'blues' %} pandora://3141422333940492872.mp3
          {% elif Playlist.lower(), 'amos lee' %} pandora://1712674494826441288.mp3
          {% elif Playlist.lower(), 'amos less' %} pandora://1712674494826441288.mp3
          {% elif Playlist.lower(), 'dishwashing' %} pandora://1649044550041233992.mp3
          {% elif Playlist.lower(), 'jack johnson' %} pandora://1451670186947013192.mp3
          {% elif Playlist.lower(), 'james taylor' %} pandora://1247104798763805256.mp3
          {% elif Playlist.lower(), 'zac brown' %} pandora://1489272784537283144.mp3
          {% elif Playlist.lower(), 'billy joel' %} pandora://2733584939730627144.mp3
          {% elif Playlist.lower(), 'tom petty' %} pandora://3611578032873040456.mp3
          {% elif Playlist.lower(), 'lyle lovett' %} pandora://44464503630359112.mp3
          {% elif Playlist.lower(), 'david grey' %} pandora://162868518528772680.mp3
          {% elif Playlist.lower(), 'the head and the heart' %} pandora://2789020817059506760.mp3
          {% elif Playlist.lower(), 'ray lamontagne' %} pandora://552400074928319048'
          {% elif Playlist.lower(), 'robert earle keen' %} pandora://1232800826796304968.mp3
          {% elif Playlist.lower(), 'donavon' %} pandora://3746286370692295240.mp3
          {% elif Playlist.lower(), 'chisrtmas acapella' %} pandora://1231256695859079752.mp3
          {% elif Playlist.lower(), 'chrismas jazz' %} pandora://6472240837192264.mp3
          {% elif Playlist.lower(), 'chistmas' %} pandora://675568853530470984.mp3
          {% elif Playlist.lower(), 'celtic christmas' %} pandora://1188289361993558600.mp3
          {% else %} pandora://3141420448449849928.mp3
