homeassistant:
  # customize:

media_player:
  - platform: squeezebox
    name: lms
    # host: 127.0.0.1
    host: 192.168.1.201
    port: 9001

# media_player:
#    - platform: cast

group:
  music:
    name: Music
    entities:
      - media_player.kitchen
      - media_player.outside
      - media_player.livingroom
      - media_player.porch
      - media_player.mbr

input_boolean:
  living_room_music:
    name: Living Room Music
    # initial: 'on'
    icon: mdi:music-note
  porch_music:
    name: Porch Music
    # initial: 'on'
    icon: mdi:music-note
  mbr_music:
    name: MBR Music
    # initial: 'on'
    icon: mdi:music-note
  outside_music:
    name: Outside Music
    # initial: 'on'
    icon: mdi:music-note

automation:
  # TODO: combine these in one
  - alias: Turn on Porch Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.porch_music
        to: 'on'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.kitchen
          command: sync
          parameters:
            - Porch
  - alias: Turn off Porch Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.porch_music
        to: 'off'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.porch
          command: sync
          parameters: [ "-" ]

  - alias: Turn on Living Room Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.living_room_music
        to: 'on'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.kitchen
          command: sync
          parameters:
            - LivingRoom
  - alias: Turn off Living Room Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.living_room_music
        to: 'off'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.livingroom
          command: sync
          parameters: [ "-" ]

  - alias: Turn on MBR Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.mbr_music
        to: 'on'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.kitchen
          command: sync
          parameters:
            - MBR
  - alias: Turn off MBR Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.mbr_music
        to: 'off'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.mbr
          command: sync
          parameters: [ "-" ]

  - alias: Turn on Outside Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.outside_music
        to: 'on'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.kitchen
          command: sync
          parameters:
            - Outside
  - alias: Turn off Outside Music
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - input_boolean.outside_music
        to: 'off'
    action:
      - service: media_player.squeezebox_call_method
        data_template:
          entity_id: media_player.outside
          command: sync
          parameters: [ "-" ]

intent_script:
  SkipSongIntent:
    speech:
      text: >
        Ok. Skipping to next track in kitchen.
    async_action: true
    action:
      service: media_player.media_next_track
      entity_id: media_player.kitchen

  PlaySongIntent:
    speech:
      text: >
        Ok. Playing music in kitchen.
    async_action: true
    action:
      service: media_player.media_play
      entity_id: media_player.kitchen

  StopSongIntent:
    speech:
      text: >
        Ok. Stopping music in kitchen.
    async_action: true
    action:
      service: media_player.media_pause
      entity_id: media_player.kitchen

  ChangePlaylistIntent:
    speech:
      text: >
        {% if   Playlist.lower() == 'jazz' %} Ok. Playing jazz in kitchen.
        {% elif Playlist.lower() == 'van morrison' %} Ok. Playing van morrison in kitchen.
        {% elif Playlist.lower() == 'blues' %} Ok. Playing blues in kitchen.
        {% elif Playlist.lower() == 'amos lee' %} Ok. Playing amos lee in kitchen.
        {% elif Playlist.lower() == 'amos less' %} Ok. Playing amos less in kitchen.
        {% elif Playlist.lower() == 'dishwashing' %} Ok. Playing dishwashing in kitchen.
        {% elif Playlist.lower() == 'jack johnson' %} Ok. Playing jack johnson in kitchen.
        {% elif Playlist.lower() == 'james taylor' %} Ok. Playing james taylor in kitchen.
        {% elif Playlist.lower() == 'zac brown' %} Ok. Playing zac brown in kitchen.
        {% elif Playlist.lower() == 'billy joel' %} Ok. Playing billy joel in kitchen.
        {% elif Playlist.lower() == 'tom petty' %} Ok. Playing tom petty in kitchen.
        {% elif Playlist.lower() == 'lyle lovett' %} Ok. Playing lyle lovett in kitchen.
        {% elif Playlist.lower() == 'david grey' %} Ok. Playing david grey in kitchen.
        {% elif Playlist.lower() == 'the head and the heart' %} Ok. Playing the head and the heart in kitchen.
        {% elif Playlist.lower() == 'ray lamontagne' %} Ok. Playing ray lamontagne in the kitchen.
        {% elif Playlist.lower() == 'robert earle keen' %} Ok. Playing robert earle keen in kitchen.
        {% elif Playlist.lower() == 'david luning' %} Ok. Playing david luning in kitchen.
        {% elif Playlist.lower() == 'david lunning' %} Ok. Playing david lunning in kitchen.
        {% elif Playlist.lower() == 'donavon' %} Ok. Playing donavan frankenreiter in kitchen.
        {% elif Playlist.lower() == 'donavon frankenreiter' %} Ok. Playing donavan frankenreiter in kitchen.
        {% elif Playlist.lower() == 'chisrtmas acapella' %} Ok. Playing chisrtmas acapella in kitchen.
        {% elif Playlist.lower() == 'chrismas jazz' %} Ok. Playing chrismas jazz in kitchen.
        {% elif Playlist.lower() == 'chistmas' %} Ok. Playing chistmas in kitchen.
        {% elif Playlist.lower() == 'celtic christmas' %} Ok. Playing celtic christmas in kitchen.
        {% else %} Sorry. I didn't recognized the {{Playlist}} playlist.
        {% endif %}
    async_action: true
    action:
      - service: system_log.write
        data_template:
          message: 'ChangePlaylistIntent: {{ Playlist.lower() }}'
          level: info
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kitchen
          media_content_id: >
            {% if   Playlist.lower() == 'jazz' %} pandora://3141420448449849928.mp3
            {% elif Playlist.lower() == 'van morrison' %} pandora://3374695489688595016.mp3
            {% elif Playlist.lower() == 'blues' %} pandora://3141422333940492872.mp3
            {% elif Playlist.lower() == 'amos lee' %} pandora://1712674494826441288.mp3
            {% elif Playlist.lower() == 'amos less' %} pandora://1712674494826441288.mp3
            {% elif Playlist.lower() == 'dishwashing' %} pandora://1649044550041233992.mp3
            {% elif Playlist.lower() == 'jack johnson' %} pandora://1451670186947013192.mp3
            {% elif Playlist.lower() == 'james taylor' %} pandora://1247104798763805256.mp3
            {% elif Playlist.lower() == 'zac brown' %} pandora://1489272784537283144.mp3
            {% elif Playlist.lower() == 'billy joel' %} pandora://2733584939730627144.mp3
            {% elif Playlist.lower() == 'tom petty' %} pandora://3611578032873040456.mp3
            {% elif Playlist.lower() == 'lyle lovett' %} pandora://44464503630359112.mp3
            {% elif Playlist.lower() == 'david grey' %} pandora://162868518528772680.mp3
            {% elif Playlist.lower() == 'the head and the heart' %} pandora://2789020817059506760.mp3
            {% elif Playlist.lower() == 'ray lamontagne' %} pandora://552400074928319048
            {% elif Playlist.lower() == 'robert earle keen' %} pandora://1232800826796304968.mp3
            {% elif Playlist.lower() == 'david luning' %} pandora://3746286370692295240.mp3
            {% elif Playlist.lower() == 'david lunning' %} pandora://3746286370692295240.mp3
            {% elif Playlist.lower() == 'donavon' %} pandora://3709080185698544200.mp3
            {% elif Playlist.lower() == 'donavon frankenreiter' %} pandora://3709080185698544200.mp3
            {% elif Playlist.lower() == 'chisrtmas acapella' %} pandora://1231256695859079752.mp3
            {% elif Playlist.lower() == 'chrismas jazz' %} pandora://6472240837192264.mp3
            {% elif Playlist.lower() == 'chistmas' %} pandora://675568853530470984.mp3
            {% elif Playlist.lower() == 'celtic christmas' %} pandora://1188289361993558600.mp3
            {% else %} pandora://3141420448449849928.mp3
            {% endif %}
          media_content_type: music

  # JoinGroupIntent:
  #   speech:
  #     text: >
  #       Ok. Starting {{ Player }}. Joining home group.
  #   async_action: true
  #   action:
  #     service: media_player.squeezebox_call_method
  #     data_template:
  #       entity_id: media_player.kitchen
  #       command: sync
  #       parameters:
  #         - {{ Player }}
  #
  # LeaveGroupIntent:
  #   speech:
  #     text: >
  #       Ok. Stopping {{ Player }}. Leaving home group.
  #   async_action: true
  #   action:
  #     service: media_player.squeezebox_call_method
  #     data_template:
  #       entity_id: media_player.{{ Player.case() }}
  #       command: sync
  #       parameters:
  #         - "-"

script:
  skip_song:
    alias: Music Skip
    sequence:
      - service: media_player.media_next_track
        entity_id: media_player.kitchen

  play_song:
    alias: Music Play
    sequence:
      - service: media_player.media_play
        entity_id: media_player.kitchen

  stop_song:
    alias: Music Stop
    sequence:
      - service: media_player.media_pause
        entity_id: media_player.kitchen
