homeassistant:
  customize:

media_player:
  - platform: squeezebox
    name: lms
    # host: 127.0.0.1
    host: 192.168.1.201
    port: 9001

# media_player:
#    - platform: cast

group:
  music:
    name: Music
    entities:
      - media_player.kitchen
      - media_player.outside
      - media_player.livingroom
      - media_player.porch
      - media_player.mbr

# automations:

intent_script:
  SkipSongIntent:
    speech:
      text: >
        Ok. Skipping to next track in kitchen.
    async_action: true
    action:
      service: media_player.media_next_track
      entity_id: media_player.kitchen
