group:
  family:
    name: Family
    entities:
      - device_tracker.mgrimes_oneplus3t
      - device_tracker.carrie_d81aebcb473e4ef7ab1e8965aecaa6c9
      - device_tracker.carrie_iphone6
      - device_tracker.campbell_iphone
      - device_tracker.carrie_iphone
      - device_tracker.mark_laptop_spike
      - device_tracker.antminer_01
      - device_tracker.campbell_iphone_mac
      - device_tracker.campbell_ipad
      - device_tracker.mark_android
      - device_tracker.whitney_ipad
      - device_tracker.carrie_ipad
      # - device_tracker.19216817
      # - device_tracker.192168119
      # - device_tracker.192168125
  present:
    name: Present
    entities:
      - binary_sensor.mark_is_home

binary_sensor:
  - platform: bayesian
    name: "Mark is home"
    prior: 0.5
    observations:
      - entity_id: 'device_tracker.mgrimes_oneplus3t'
        prob_given_true: 0.7
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.mark_android'
        prob_given_true: 0.7
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'

automation:
  - alias: 'Mark is Arriving'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.mark_is_home
        from: 'off'
        to: 'on'
    action:
      - service: notify.pushover
        data_template:
          title: 'Marks location changed'
          message: >
            Mark is {{ trigger.to_state.state }}.
            Was away for {{ ( as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed) ) / 60 }} minutes.
            This changed {{ trigger.to_state.last_changed }}.
            This updated {{ trigger.to_state.last_updated }}.
            Last changed {{ trigger.from_state.last_changed }}.
            Last updated {{ trigger.from_state.last_updated }}.
      # We've been gone for at least 20 minutes
      - condition: template
        value_template: >
          {{ (( as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed) ) / 60) > 20 }}
      - service: notify.pushover
        data_template:
          title: 'Marks location changed'
          message: >
            Mark is {{ trigger.to_state.state }}.
            This changed {{ trigger.to_state.last_changed }}.
            This updated {{ trigger.to_state.last_updated }}.
            Last changed {{ trigger.from_state.last_changed }}.
            Last updated {{ trigger.from_state.last_updated }}.

  - alias: 'Home Mode when Arriving'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id:
          - device_tracker.mgrimes_oneplus3t
          - device_tracker.carrie_d81aebcb473e4ef7ab1e8965aecaa6c9
          - device_tracker.carrie_iphone6
          - device_tracker.campbell_iphone
          - device_tracker.carrie_iphone
          # - device_tracker.mark_laptop_spike
          - device_tracker.campbell_iphone_mac
          # - device_tracker.campbell_ipad
          - device_tracker.mark_android
          # - device_tracker.whitney_ipad
          # - device_tracker.carrie_ipad
        to: 'home'
        for:
          minutes: 5
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.home_mode
