# -------------------------------------------
#  Clean data for the Floorplan UI.
# -------------------------------------------
#
homeassistant:
  customize_glob:

    "sensor.clock_*":
      hidden: true
      homebridge_hidden: true


# ---Sensor for Time and Date.-----------------------------
sensor:

  - platform: template
    sensors:
      clock_time:
        friendly_name: 'Clock Time'
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_am_pm:
        friendly_name: 'AM/PM'
        value_template: >-
          {{now().strftime("%p")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_day:
        friendly_name: 'Day'
        value_template: >-
          {{now().strftime("%A")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_date:
        friendly_name: 'Clock Date'
        value_template: >-
          {{now().strftime("%B")}} {{now().strftime("%d")}}, {{now().year}}
