homeassistant:
  customize:
    sensor.pws_weather_1d:
      friendly_name: WU Forcast

group:
  weather_simple:
    name: Weather
    entities:
      - sensor.pws_weather_1d
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed

  weather_wu:
    name: Weather Underground
    entities:
      - sensor.pws_alerts
      - sensor.pws_dewpoint_f
      - sensor.pws_precip_today_in
      - sensor.pws_precip_1d_in
      - sensor.pws_precip_2d_in
      - sensor.pws_temp_f
      - sensor.pws_weather
      - sensor.pws_weather_1d
      - sensor.pws_temp_high_1d_f
      - sensor.pws_temp_low_1d_f

  weather_sun:
    name: Sun
    entities:
      - sun.sun
      - sensor.yr_symbol

  weather_ds:
    name: DarkSky
    entities:
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_hourly_summary

sensor:
  - platform: yr

  - platform: wunderground
    api_key: !secret wu_api_key
    monitored_conditions:
      - alerts
      - dewpoint_f
      - temp_f
      - precip_today_in
      - precip_1d_in
      - precip_2d_in
      - weather
      - weather_1d
      - temp_high_1d_f
      - temp_low_1d_f

  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      # - summary
      # - precip_type
      - precip_intensity
      - precip_intensity_max
      - temperature
      # - dew_point
      - wind_speed
      # - wind_bearing
      - cloud_cover
      - humidity
      # - nearest_storm_distance
      - minutely_summary
      # - pressure
      # - visibility
      # - ozone
      - uv_index
      - hourly_summary
